### ISSUE TITLE
How to handle inconsistent cognateset IDs

### ISSUE THREAD

**Issue by xrotwang** [lexibank/abvd#1]
The word for "Twenty" in language [Palembang Malay](https://abvd.shh.mpg.de/austronesian/language.php?id=655) is assigned to cognate set `3.6`. This may mean `36`, or `3 , 6`.
It certainly is a good example why we shouldn't sluggify identifiers, but how to correct? Fix in the source?

**Comment by SimonGreenhill** [comment]
I've fixed this in the source (="3, 6"). In terms of lexibank, I think we should be liberal with warnings and raising errors. Perhaps the way here is to produce an error ('unable to parse cognate set "xxx" in language y item z')
