### ISSUE TITLE
Dayak Ngaju /salawi/ is 'Twenty-Five', not 'Twenty'

### ISSUE THREAD

**Issue by barlowrussell** [lexibank/abvd#13]
For Dayak Ngaju [ngaj1237], the form /salawi/ is glossed as 'Twenty', but it should be glossed as 'Twenty-Five' (Suryanyahu 2013: 130). (A loan from Javanese?) By all accounts, '20' in Dayak Ngaju is a reflex of *duha *puluq.

**Comment by SimonGreenhill** [comment]
updated, thanks Russell
