### ISSUE TITLE
Wrong glottocode for 1686 (Betawi Malay (Tengahan dialect))

### ISSUE THREAD

**Issue by barlowrussell** [lexibank/abvd#17]
Hello, language ID 1686 (Betawi Malay (Tengahan dialect)) currently has the glottocode lame1259 (for Lamenu-Lewo), which doesn't seem right. It should be something more along the lines of beta1252 (for Betawi) ... although the terminology and classifications surrounding "Betawi" and various other Malayic varieties spoken in and around Jakarta is a mess.

**Comment by SimonGreenhill** [comment]
Hmm.. Suspect it's [Tangerang: tang1384](https://glottolog.org/resource/languoid/id/tang1384)
