### ISSUE TITLE
Typo in 853-201_five-1 (Wetan 'five'): Should be <wolima>, not <wolina>

### ISSUE THREAD

**Issue by barlowrussell** [lexibank/abvd#20]
The form given for 'five' in Wetan [luan1263] should be "wolima"; there appears to be a typo (with medial *n instead of "m"). See Josselin de Jong (1987: 179, 272, 294).

de Josselin de Jong, Jan Petrus Benjamin. 1987. _Wetan fieldnotes: Some eastern Indonesian texts with linguistic notes and a vocabulary_ (Verhandelingen van het Koninklijk Instituut voor Taal-, Land- en Volkenkunde 130). Dordrecht: Foris Publications.

**Comment by SimonGreenhill** [comment]
fixed upstream.
