### ISSUE TITLE
Typo in 1387-201_five-1 (Pak 'five'): Should be <nuron>, not <muron>

### ISSUE THREAD

**Issue by barlowrussell** [lexibank/abvd#21]
The form given for 'five' in Pak [pakt1239] should be "nuron"; there appears to be a typo (with initial *m instead of "n"). See Smythe & Z'graggen (1975: 185).

Also, speaking of this source, <Z'graggen’> should be spelled with a lowercase <g> in the Source/Author and Notes sections.

Oh, and Simon, you mentioned fixing typos upstream ... is there a more convenient place than here for me to register these typos when I see them?

**Comment by SimonGreenhill** [comment]
Hi Russell, thanks this is fixed in the main ABVD site, and will percolate here next time I update the CLDF dataset. 

It's probably easiest to just email me directly to get things fixed. I'm keen to get any typos fixed.

**Comment by barlowrussell** [comment]
Hi Simon -- great! Sure thing, I'll email next time I find something :)
