### ISSUE TITLE
Include classification in LanguageTable?

### ISSUE THREAD

**Issue by xrotwang** [lexibank/abvd#5]
As far as I can see, the ABVD [classification](https://abvd.shh.mpg.de/austronesian/classification.php) isn't included in the CLDF dataset yet. If we want to re-implement the php app in clld and load data from the CLDF, this might be necessary.

**Comment by SimonGreenhill** [comment]
Hmm. The ABVD has a 'bespoke' classification in some places (i.e. linguists told me that languages x and y should go together), but it's probably best to just synchronise this with glottolog?

**Comment by xrotwang** [comment]
Dunno. If we don't include it, it will be lost sooner or later.

**Comment by SimonGreenhill** [comment]
yeah. how about we let it go

**Comment by xrotwang** [comment]
Yes, I'm a big fan of Kuhn-loss.

Simon J Greenhill <notifications@github.com> schrieb am Do., 12. März 2020,
12:57:

**Comment by SimonGreenhill** [comment]
closing as we currently don't include it, as decided.
