### ISSUE TITLE
Consider split or new Glottocode for 'Angkola / Mandailing' [lang id 863]

### ISSUE THREAD

**Issue by Bibiko** [lexibank/abvd#9]
https://github.com/lexibank/abvd/blob/master/cldf/languages.csv#L1986
current Glottocode bata1290 refers to Batak Angkola **only**

either new:

**Angkola / Mandailing** angk1248 - https://glottolog.org/resource/languoid/id/angk1248

or split into 

**Batak Angkola** bata1290 - https://glottolog.org/resource/languoid/id/bata1290
**Batak Mandailing** bata1291 - https://glottolog.org/resource/languoid/id/bata1291

if the data are the same for both varieties

**Comment by SimonGreenhill** [comment]
thanks @Bibiko  -- I've split the two lists in the database.
